spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://postgres:5432/db
    username: z
    password: pp18
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 8
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
    debug:
      enabled: true
  mail:
    host: smtp.office365.com
    port: 587
    username: CDRapplication@hotmail.com
    password: cdrtest18
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    version: 1.0.0

logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.hibernate.engine.internal: WARN
    org.hibernate.engine.spi: WARN

server:
  port: 8080
