spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://postgres:5432/db
    username: z
    password: pp18
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
    debug:
      enabled: true
logging:
  level:
    root: DEBUG
server:
  port: 8080
