spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/cdrsdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
